default: &default
  adapter: postgresql
  encoding: unicode
  #host: localhost
  #port: 5432
  # pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  #username: maru
  #password: maru

development:
  <<: *default
  database: app_name_development

test:
  <<: *default
  database: app_name_test

staging:
  <<: *default
  database: app_name_staging

production:
  <<: *default
  database: app_name_production